# Site settings
title: Zero to One Solutions
subtitle: "Creating Tomorrow, Today"
locale: "en-US"
logo: "/assets/images/logo.png"
name: "Scaled Evolution"
email: contact@scaledevolution.com
description: >- # this means to ignore newlines until "baseurl:"
  At Scaled Evolution, we are trailblazers in the realm of software development and consultancy,
  empowering businesses to thrive in the digital era. Our mission is to help companies build cutting-edge,
  scalable, and enterprise-grade applications that elevate their performance and drive success.
# twitter_username: ScaledEvolution
github_username: ScaledEvolution

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
repository: ScaledEvolution/scaledevolution.github.io
url: "https://scaledevolution.com"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Amsterdam"

search: false
atom_feed:
  hide: true

include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Aykut Aras"
  avatar : "https://www.gravatar.com/avatar/7c2e00952d91de9e038cefd2d68c88db?s=200"
  bio    : >-
    Lead Software Engineer /
    Senior DevOps Engineer /
    Serverless Advocate
  location: "Eindhoven, The Netherlands"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aykutaras.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/aykutaras"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aykutaras"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ScaledEvolution"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ScaledEvolution"

collections:
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
