# Site settings
title: Zero to One Solutions
subtitle: "Creating Tomorrow, Today"
locale: "en-US"
logo: "/assets/images/logo.png"
name: "Scaled Evolution"
email: contact@zerotoone.solutions
description: >- # this means to ignore newlines until "baseurl:"
  As a parent company, we serve as an idea incubator and design lab, fostering creativity and innovation across various industries. While we have diverse interests, our focus remains on sports and the advancement of sporting equipment.
github_username: romdj

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
repository: Zero-to-One-Solutions.github.io
url: "https://zerotoone.solutions"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Amsterdam"

search: false
atom_feed:
  hide: true

include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Aykut Aras"
  avatar : "https://www.gravatar.com/avatar/7c2e00952d91de9e038cefd2d68c88db?s=200"
  bio    : >-
    Solution Architect /
    Innovation Factory
    
  location: "Brussels, Belgium"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://zerotoone.solutions"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Zero-to-One-Solutions"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Zero-to-One-Solutions"

collections:
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
